name: Validate generated HTML and CSS
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Prepare java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: 2.12.0

      - name: Build site
        run: lein build-site

      - name: Validate HTML and CSS
        uses: anishathalye/proof-html@v2.2.3
        with:
          directory: ./firebase/public
          enforce_https: false
          disable_external: true
          tokens: |
            {"https://github.com": "${{ secrets.GITHUB_TOKEN }}"}
          validator_ignore: ".*disable[pP]icture[iI]n[pP]icture.*not allowed on element.*video.*at this point.*|.*skipping.*heading level."
